export enum MessageType {
  LOST_STREAK = 'LOST_STREAK',
  TIMES_UP = 'TIMES_UP',
  GAME_LOST_WORD_SOLUTION = 'LOST_WORD_SOLUTION',
  EASTER_EGG = 'EASTER_EGG',
  NO_ENOUGH_LETTERS = 'NO_ENOUGH_LETTERS',
  WORD_ALREADY_TRIED = 'WORD_ALREADY_TRIED',
  WORD_IS_NOT_VALID = 'WORD_IS_NOT_VALID',
}
